### ISSUE TITLE
Execution of TFS VNext release using powershell

### ISSUE THREAD

**Issue by MadhaviPallem** [Mexia/PowerShell#4]
$body = @{
    "definitionId"= 18;
    "artifacts"= 
    @{
        "alias"= "Tests";
        "instanceReference"= @{
            "id"= 152;
            "name"= "BuildTests_20180626.5"
        }
    }
}
$Uri = "XXXX/_apis/release/releases?api-version=3.0-preview.2"
$releaseresponse = Invoke-RestMethod -Method Post -UseDefaultCredentials -ContentType application/json -Uri $Uri -Body (ConvertTo-Json $body -depth 50) 

The above threw below error message when executed in powershell

Invoke-RestMethod : {"$id":"1","innerException":null,"message":"VS402936: Release definition with id 0 does not exist. Specify a valid id and try 
again.","typeName":"Microsoft.VisualStudio.Services.ReleaseManagement.Data.Exceptions.ReleaseDefinitionNotFoundException, 
Microsoft.VisualStudio.Services.ReleaseManagement2.Data","typeKey":"ReleaseDefinitionNotFoundException","errorCode":0,"eventId":3000}
At C:\InstallationTests\VNext\GridTests.ps1:15 char:20
+ $releaseresponse = Invoke-RestMethod -Method Post -UseDefaultCredentials -Conten ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by mattcorr** [comment]
Hello.

I am not sure how this relates to the PowerShell that is published so far in this git repo?

You might want to review [this link](https://docs.microsoft.com/en-us/rest/api/vsts/release/releases/create?view=vsts-rest-4.1) or another one with the version you are using to see if the content in your body is correct.

From what I can see, is version 4.1 of the REST API available on your TFS VNext?

Also your `$body` structure is more a list of hashtables, rather than objects.

If I look at what `$body` is, I get: 
```
PS C:\Work> $body

Name                           Value    
----                           ----- 
definitionId                   18 
artifacts                      {instanceReference, alias}     
```

But you cast to `PSCustomObject` like this:
```powershell
$body2 = [PSCustomObject]@{
"definitionId"= 18;
"artifacts"=
[PSCustomObject]@{
"alias"= "Tests";
"instanceReference"= [PSCustomObject]@{
"id"= 152;
"name"= "BuildTests_20180626.5"
}
}
}
```
you end up with
```
PS C:\Work> $body2

definitionId artifacts   
------------ --------- 
          18 @{alias=Tests; instanceReference=}
```
Which I think is more what the JSON structure should be?
See if that helps.
